---
object_type: instance
version: 1.0
object:
  attributes:
    display_name: Provision RHEV VM from Template
    name: redhat_template
    inherits: 
    description: 
  fields:
  - AcquireMACAddress:
      value: "#/Infrastructure/VM/Provisioning/StateMachines/Methods/GenerateMACAddress#${/#miq_provision.source.vendor}"
  - AcquireIPAddress:
      value: "/Integration/BlueCat/AddressManager/BlueCat_AcquireIPAddress2"
  - Provision:
      value: "/Infrastructure/VM/Provisioning/StateMachines/Methods/Provision"
  - CheckProvisioned:
      value: "/Infrastructure/VM/Provisioning/StateMachines/Methods/CheckProvisioned"
